server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/software_design?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 2005106
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

app:
  jwt:
    secret: teaching-platform-secret-2026
    expire-days: 7
